export const DATA_LOADING = 'DATA_LOADING';
export const DATA_LOADED = 'DATA_LOADED';

export const LOAD_DATASETS = 'LOAD_DATASETS';
export const ADD_DATASET = 'ADD_DATASET';
export const UPDATE_DATASET_DETAILS = 'UPDATE_DATASET_DETAILS';
export const ADD_FILE_TO_DATASET = 'ADD_FILE_TO_DATASET';
export const DELETE_FILE_FROM_DATASET = 'DELETE_FILE_FROM_DATASET';

export const LOAD_TRAININGS = 'LOAD_TRAININGS';
export const ADD_TRAINING = 'ADD_TRAINING';
export const UPDATE_TRAINING_PROGRESS = 'UPDATE_TRAINING_PROGRESS';
export const UPDATE_TRAINING_FORM_DATA = 'UPDATE_TRAINING_FORM_DATA';
export const UPDATE_TRAINING_STATUS = 'UPDATE_TRAINING_STATUS';

export const LOAD_EVALUATIONS = 'LOAD_EVALUATIONS';
export const ADD_EVALUATION = 'ADD_EVALUATION';
export const UPDATE_EVALUATION_FORM_DATA = 'UPDATE_TRAINING_FORM_DATA';
export const UPDATE_EVALUATION_STATUS = 'UPDATE_EVALUATION_STATUS';