# Generated by Django 3.1 on 2020-08-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='name',
            new_name='upload_id',
        ),
        migrations.AddField(
            model_name='upload',
            name='dataset_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
